database:
  query:
    create: CREATE TABLE IF NOT EXISTS posts (link varchar(256) PRIMARY KEY, posttime integer NOT NULL, keyword text, timestamp integer DEFAULT (strftime('%s', 'now')));
    insert: INSERT INTO posts(link,posttime,keyword) VALUES(?,?,?)
    select: SELECT * FROM posts

webdriver:
  chromeoptions: ["--start-maximized", "--disable-notifications"]
  wait:
    time: 10  #seconds
  sleep: 2    #seconds
  maxtries: 5

input:
  url: https://www.facebook.com/groups/{}/?sorting_setting=RECENT_ACTIVITY
  limit: 50 #no. of posts to crawl in a group
  thread: 2 #max number of threads
  groups: [
    'flatsandflatmatesbanglore',
    'FlatsandFlatmatesBangaloreChapter'
  ]
  keywords: [
    'bellandur',
    'rmz',
    'ecospace',
    'eco space',
    'kalyani',
    'orr',
    'outer ring road',
    'kadubeesanahalli',
    'cessna',
    'yemalur',
    'jp morgan',
    'panathur',
    'microsoft',
    'agrahara',
    'adarsh palm retreat',
    'jcr layout',
    'chandra layout'
  ]

  #case sensitivity is handled in code
  #IMPORTANT: 'male only' will match 'female only' also because it contains the first string
  exceptions: [
    'female only',
    'females only',
    'only female',
    'female flatmate',
    'femaleflatmate',
    'female flat mate',
    'female room',
    'girls only',
    'hi girls',
    'interested girls',
    'only girls',
    'family only',
    'only family',
    'btm',
    'rmz infinity'
  ]

output:
  directory: output/
  query: SELECT * FROM posts ORDER BY posttime DESC
  timeformat: "%d-%m-%Y %I:%M%p"

logs:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - [%(name)s] [%(levelname)s] - %(message)s'
      datefmt: '%d%b%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: logs/app.log
      mode: a
  loggers:
    __main__:
      level: DEBUG
      handlers: [console, file]
      propagate: no
  root:
    level: DEBUG
    handlers: [file]