database:
  query:
    create: CREATE TABLE IF NOT EXISTS posts (link varchar(256) PRIMARY KEY, posttime integer NOT NULL, keyword text, body text, timestamp integer DEFAULT (strftime('%s', 'now')));
    insert: INSERT INTO posts(link,posttime,keyword,body) VALUES(?,?,?,?)
    select: SELECT * FROM posts

webdriver:
  chromeoptions: ["--headless", "--window-size=1367x768", "--start-maximized", "--disable-notifications"]
  wait:
    time: 30  #seconds
  sleep: 2    #seconds
  maxtries: 7

input:
  url: https://www.facebook.com/groups/{}/?sorting_setting=RECENT_ACTIVITY
  limit: 50  #no. of posts to crawl in a group
  thread: 2  #max number of threads
  groups: [
    'flatsandflatmatesbanglore',
    'FlatsandFlatmatesBangaloreChapter',
    'cbuddy.roommates.bangalore',
    '575327112671225',
    '1112186535519650',
    'BangaloreFlatmates',
    '543987232323064',
    '337835370175255',
    '141404379916935',
    '329320681157074',
    '2020505841540002'
  ]
  keywords: [
    'bellandur',
    'rmz',
    'ecospace',
    'eco space',
    ' orr ',
    'outer ring road',
    'kadubeesanahalli',
    'cessna',
    'yemalur',
    'jp morgan',
    'panathur',
    'microsoft',
    'agrahara',
    'adarsh palm retreat',
    'jcr layout',
    'chandra layout'
  ]

  #case sensitivity is handled in code
  #IMPORTANT: 'male only' will match 'female only' also because it contains the first string
  exceptions: [
    'male flatmate', #female flatmates as well
    'roommate',
    'looking for a flatmate',
    'single occupancy',
    'singleoccupancy',
    'double occupancy',
    'female only',
    'females only',
    'only female',
    'female room',
    'for a female',
    'girls only',
    'interested girls',
    'only girls',
    'family only',
    'only family',
    'rmz infinity'
  ]

output:
  directory: output/
  outputfileprefix: output
  newpostsfileprefix: newposts
  query: SELECT * FROM posts ORDER BY posttime DESC
  timeformat: "%d-%m-%Y %I:%M%p"
  sizeofbody: 100 #characters

logs:
  version: 1
  formatters:
    html:
      format: '%(asctime)s - [<font>%(name)s</font>] [<font>%(levelname)s</font>] - %(message)s'
      datefmt: '%d%b%Y %H:%M:%S'
    simple:
      format: '%(asctime)s - [%(name)s] [%(levelname)s] - %(message)s'
      datefmt: '%d%b%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: html
      filename: logs/app.html
      mode: a
  loggers:
    __main__:
      level: INFO
      handlers: [console, file]
      propagate: no
  root:
    level: INFO
    handlers: [file]